-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analyses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  overall_score double precision,
  investment_readiness text,
  value_proposition_score double precision,
  customer_segments_score double precision,
  channels_score double precision,
  revenue_score double precision,
  costs_score double precision,
  key_resources_score double precision,
  key_activities_score double precision,
  key_partners_score double precision,
  team_score double precision,
  expert_insights jsonb NOT NULL,
  consensus_findings jsonb NOT NULL,
  growth_plan jsonb NOT NULL,
  recommendations jsonb NOT NULL,
  financial_forecast jsonb NOT NULL,
  ai_model text NOT NULL DEFAULT 'gpt-4-turbo'::text,
  tokens_used integer,
  processing_time integer,
  status text NOT NULL DEFAULT 'pending'::text,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT analyses_pkey PRIMARY KEY (id),
  CONSTRAINT analyses_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.exported_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  analysis_id uuid NOT NULL,
  report_type text NOT NULL,
  format text NOT NULL,
  language text NOT NULL DEFAULT 'en'::text,
  file_url text,
  file_size integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT exported_reports_pkey PRIMARY KEY (id),
  CONSTRAINT exported_reports_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT exported_reports_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id)
);
CREATE TABLE public.project_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  version_number text NOT NULL,
  snapshot jsonb NOT NULL,
  changes_description text,
  changed_fields jsonb,
  overall_score double precision,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT project_versions_pkey PRIMARY KEY (id),
  CONSTRAINT project_versions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  industry text,
  stage text,
  value_prop_problem text,
  value_prop_solution text,
  value_prop_uniqueness text,
  value_prop_measurable text,
  value_prop_advantages jsonb,
  customer_primary_segment text,
  customer_tam text,
  customer_sam text,
  customer_som text,
  customer_geography text,
  customer_wtp text,
  customer_avg_check double precision,
  channels_acquisition jsonb,
  channels_sales text,
  channels_cac double precision,
  channels_cac_description text,
  channels_marketing text,
  channels_funnel text,
  revenue_projected_12m double precision,
  revenue_streams jsonb,
  revenue_pricing text,
  cost_breakdown text,
  cost_gross_margin double precision,
  arpu double precision,
  customer_lifetime double precision,
  contribution_margin double precision,
  cost_runway integer,
  funding_raised double precision,
  funding_sought double precision,
  funding_sources jsonb,
  use_of_funds jsonb,
  team_founders text,
  team_key_hires text,
  team_specialists text,
  team_gaps text,
  resources_physical text,
  resources_intellectual text,
  resources_needed text,
  resources_dependencies text,
  activities_production text,
  activities_innovation text,
  activities_platform text,
  activities_marketing text,
  activities_operations text,
  partners_strategic jsonb,
  competitors text,
  competition_why_choose text,
  competition_defensibility text,
  risks text,
  traction text,
  growth_plan text,
  growth_new_markets text,
  growth_payback_period text,
  growth_targets_12m text,
  growth_targets_24m text,
  growth_targets_36m text,
  status text NOT NULL DEFAULT 'draft'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  name text,
  password text NOT NULL,
  plan text NOT NULL DEFAULT 'free'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);