import { ExpertField, ExpertInsight, ProjectVersionDB, ConsensusFindings, BlockScores, RecommendationPriority, Recommendation, GrowthPhase, MonthlyProjection } from './useAnalizeStore.types';

export const TEST_ANALYSIS = {
  project: {
    id: 'test-project-1',
    name: 'v24',
    industry: 'Healthtech',
    stage: 'MVP / Pre-seed',
  },
  analysis: {
    scores: {
      overall: 82,
      readiness: 'Nearly Ready',
      blocks: {
        valueProposition: 85,
        customerSegments: 78,
        channels: 68,
        revenue: 88,
        costs: 75,
        keyResources: 70,
        keyActivities: 75,
        keyPartners: 65,
        team: 80,
      } as BlockScores,
    },
    benchmark: {
      percentile: 24,
      betterThan: 76,
    },
    consensus: {
      findings: {
        topStrengths: [
          'Exceptional unit economics: LTV/CAC 32.4x (all 6 experts agree)',
          'Large market opportunity: €2.5B TAM with 15% CAGR (5 experts)',
          'Strong product-market fit: NPS 75, 90-day retention 87% (5 experts)',
          'Proven value proposition: 70% time savings validated (6 experts)',
          'Solid founding team with domain expertise (4 experts)',
        ],
        topWeaknesses: [
          'Channel strategy needs scaling beyond founder-led sales (5 experts)',
          'Geographic expansion plan too ambitious for resources (4 experts)',
          'Technical debt accumulating in core product (3 experts)',
        ],
      } as ConsensusFindings,
    },
    experts: {
      list: [
        {
          field: ExpertField.FINANCIAL,
          name: 'Maria Rodriguez',
          role: 'Financial Expert',
          avatar: '💰',
          summary: 'Excellent unit economics (LTV/CAC 32.4x) with strong path to profitability.',
          confidence: 88,
          keyFindings: [
            'LTV/CAC ratio of 32.4x is exceptional (benchmark: >3)',
            'Gross margin of 80% is strong for B2B SaaS',
            'Payback period of 0.6 months demonstrates efficient capital deployment',
            'Monthly burn rate well-controlled at €7,000',
          ],
          concerns: [
            'Current runway of 11 months should be extended to 18+ months',
            'Break-even projection at month 18 depends on consistent 15% MoM growth',
          ],
          recommendations: [
            'Secure €75K bridge round to extend runway to 21 months',
            'Build 3-scenario financial model (base, optimistic, pessimistic)',
            'Set up automated financial dashboards for investor updates',
          ],
        },
        {
          field: ExpertField.MARKET,
          name: 'David Chen',
          role: 'Market Analyst',
          avatar: '📊',
          summary: 'Large market opportunity (€2.5B TAM) with improving customer validation.',
          confidence: 85,
          keyFindings: [
            'TAM of €2.5B represents venture-scale opportunity',
            'SMB HR tech market growing at 15% CAGR',
            'Customer validation improved from 5 to 25 pilot customers',
            'Clear ICP: 50-500 employee companies in tech/professional services',
          ],
          concerns: [
            'Geographic expansion plan (UK, DE, NL) may dilute focus',
            'Competitive landscape intensifying with 3 new entrants in 2025',
          ],
          recommendations: [
            'Focus exclusively on UK market for first 12 months',
            'Conduct quarterly competitive analysis',
            'Build customer advisory board with 5-7 key customers',
          ],
        },
        {
          field: ExpertField.PRODUCT,
          name: 'Sarah Thompson',
          role: 'Product Expert',
          avatar: '🎯',
          summary: 'Strong value proposition with proven 70% time savings and high NPS of 75.',
          confidence: 90,
          keyFindings: [
            'Clear pain point: HR managers waste 40h/month on manual tasks',
            'Quantified value: reduce hiring time from 45 to 10 days',
            'Product NPS of 75 indicates strong product-market fit',
            '10x improvement vs alternatives (not incremental)',
          ],
          concerns: [
            'Feature roadmap lacks prioritization framework',
            'Technical debt accumulating in core hiring module',
          ],
          recommendations: [
            'Implement RICE prioritization for product roadmap',
            'Allocate 20% of dev capacity to technical debt reduction',
            'Launch beta program for top 3 requested features',
          ],
        },
        {
          field: ExpertField.MARKETING,
          name: 'Alex Kumar',
          role: 'Marketing Expert',
          avatar: '📈',
          summary: 'Validated go-to-market channels with CAC of €55 and improving conversion rates.',
          confidence: 82,
          keyFindings: [
            'CAC of €55 is excellent for B2B SaaS (LTV/CAC = 32.4x)',
            'Product Hunt launch achieved #2 Product of the Day',
            'LinkedIn ads converting at 4.2% (industry avg: 2.5%)',
            'Content marketing generating 40% of qualified leads',
          ],
          concerns: [
            'Heavy reliance on founder-led sales (not scalable)',
            'Email marketing underutilized (only 15% open rate)',
            'No referral program despite high NPS',
          ],
          recommendations: [
            'Launch referral program (20% discount for referrer + referee)',
            'Hire VP Sales to build repeatable sales process',
            'A/B test email subject lines to improve open rates to 25%+',
          ],
        },
        {
          field: ExpertField.RISK,
          name: 'James Foster',
          role: 'Risk Manager',
          avatar: '⚠️',
          summary: 'Well-managed risk profile with effective mitigation strategies in place.',
          confidence: 87,
          keyFindings: [
            'Critical risks identified and documented',
            'Mitigation plans established for top 5 risks',
            'Risk register reviewed monthly',
            'Contingency budget of €20K maintained',
          ],
          criticalRisks: [
            {
              category: 'technical',
              description: 'OpenAI API dependency: 2-3x price increase would impact margins',
              likelihood: 'medium',
              impact: 'high',
              mitigation: 'Built Claude/Gemini fallback; testing alternative providers',
            },
            {
              category: 'market',
              description: 'Economic downturn reducing SMB hiring budgets',
              likelihood: 'medium',
              impact: 'high',
              mitigation: 'Diversifying into employee onboarding (recession-resistant)',
            },
            {
              category: 'team',
              description: 'Key person risk: CTO holds all technical knowledge',
              likelihood: 'low',
              impact: 'critical',
              mitigation: 'Documentation in progress; planning contractor backup',
            },
          ],
          concerns: [
            'Regulatory risk: GDPR compliance for EU expansion not fully assessed',
            'Competition from well-funded startups (BambooHR raised $50M)',
          ],
          recommendations: [
            'Conduct GDPR compliance audit with legal counsel',
            'Build competitive moat through proprietary AI training data',
            'Consider key person insurance for founders',
          ],
        },
        {
          field: ExpertField.OPERATIONS,
          name: 'Lisa Wang',
          role: 'Operations Expert',
          avatar: '⚙️',
          summary: 'Strong founding team with complementary skills and clear execution track record.',
          confidence: 86,
          keyFindings: [
            'Founders have domain expertise (10 years HR, 8 years engineering)',
            'Team executed on 90% of Q1 objectives',
            'Clear roles and responsibilities established',
            'Advisor network includes 2 VPs from unicorn SaaS companies',
          ],
          concerns: [
            'No sales expertise on founding team',
            'Customer success process not documented',
            'Hiring plan lacks specific timelines and compensation bands',
          ],
          recommendations: [
            'Hire VP Sales by Month 6 (budget €80K + equity)',
            'Document customer onboarding playbook',
            'Create hiring roadmap with job descriptions and salary ranges',
          ],
        },
      ] as ExpertInsight[],
    },
    recommendations: {
      list: [
        {
          id: 'rec-1',
          priority: RecommendationPriority.CRITICAL,
          category: 'team',
          title: 'Hire VP Sales',
          description: 'Founder-led sales won\'t scale beyond €20K MRR. Need experienced sales leader to build repeatable process.',
          actionSteps: [
            'Define VP Sales job description and compensation (€80K + 1-2% equity)',
            'Post on AngelList, LinkedIn, and startup job boards',
            'Screen 20+ candidates, interview top 5',
            'Check references and conduct trial project',
            'Onboard VP Sales with 30-60-90 day plan',
          ],
          expectedImpact: 'Channels score: 68 → 85 (+17 pts), Overall: 82 → 87 (+5 pts)',
          effort: 'High',
          timeline: '8 weeks',
          expertsSupporting: ['marketingExpert', 'opsExpert', 'financialExpert', 'riskManager', 'marketAnalyst', 'productExpert'],
        },
        {
          id: 'rec-2',
          priority: RecommendationPriority.CRITICAL,
          category: 'costs',
          title: 'Extend Financial Runway',
          description: '11 months runway creates pressure and limits strategic options. Extend to 18+ months for safety.',
          actionSteps: [
            'Prepare bridge round deck highlighting traction metrics',
            'Reach out to existing angels for €75K bridge at €3M cap',
            'Negotiate terms (2-week deadline)',
            'Close bridge round and update cap table',
          ],
          expectedImpact: 'Costs score: 75 → 88 (+13 pts), reduces financial risk to LOW',
          effort: 'Medium',
          timeline: '4 weeks',
          expertsSupporting: ['financialExpert', 'riskManager', 'opsExpert', 'marketAnalyst'],
        },
        {
          id: 'rec-3',
          priority: RecommendationPriority.HIGH,
          category: 'channels',
          title: 'Launch Referral Program',
          description: 'NPS of 75 indicates customers love product. Leverage this for viral growth.',
          actionSteps: [
            'Design referral mechanics: 20% discount for both parties',
            'Build referral tracking in dashboard',
            'Create email drip campaign to promote referrals',
            'Test with top 10 customers',
            'Scale to all customers if conversion > 15%',
          ],
          expectedImpact: 'Channels score: 68 → 78 (+10 pts), 20-30% of new customers from referrals',
          effort: 'Medium',
          timeline: '3 weeks',
          expertsSupporting: ['marketingExpert', 'productExpert', 'financialExpert'],
        },
      ] as Recommendation[],
    },
    growthPlan: {
      phases: {
        phase1: {
          name: 'Market Focus & Sales Scaling',
          duration: 'Months 1-3',
          goals: [
            'Hire VP Sales and close first 3 enterprise deals',
            'Launch referral program and achieve 20% referral rate',
            'Reach 50 paying customers (€4,950 MRR)',
            'Maintain 90%+ customer satisfaction (NPS > 70)',
          ],
          keyActions: [
            'Recruit and onboard VP Sales',
            'Build sales playbook and email sequences',
            'Launch referral program',
            'Focus exclusively on UK market',
            'Close €75K bridge round',
          ],
          budget: '€27,000',
          teamSize: '2 founders + 1 developer + 1 VP Sales',
          successMetrics: ['50 customers', '€4,950 MRR', 'NPS > 70', 'VP Sales hired'],
        },
        phase2: {
          name: 'Product Expansion & Seed Round',
          duration: 'Months 4-6',
          goals: [
            'Raise €300K seed round at €4M valuation',
            'Launch employee onboarding module (2nd product line)',
            'Reach 100 paying customers (€9,900 MRR)',
            'Hire Customer Success Manager',
          ],
          keyActions: [
            'Prepare seed deck with traction metrics',
            'Pitch 30+ VCs (target: SaaS/HR tech funds)',
            'Ship onboarding module to 20 beta customers',
            'Scale paid acquisition (LinkedIn, Google Ads)',
            'Document customer success playbook',
          ],
          budget: '€36,000',
          teamSize: '5 people (+ Customer Success Manager)',
          successMetrics: ['€300K raised', '100 customers', '€9,900 MRR', 'Onboarding launched'],
        },
        phase3: {
          name: 'Scale & International',
          duration: 'Months 7-12',
          goals: [
            'Scale to 200 customers (€19,800 MRR)',
            'Expand to Germany market (localization)',
            'Achieve 85% gross retention rate',
            'Prepare for Series A',
          ],
          keyActions: [
            'Launch German version of product',
            'Hire German-speaking sales rep',
            'Build integrations (HRIS, ATS)',
            'Optimize onboarding funnel',
            'Create investor pipeline for Series A',
          ],
          budget: '€72,000',
          teamSize: '8-10 people',
          successMetrics: ['200 customers', '€19,800 MRR', 'Germany: 30 customers', '85% retention'],
        },
      } as Record<string, GrowthPhase>,
    },
    financialForecast: {
      unitEconomics: {
        ltv: 1782,
        cac: 55,
        ltvCacRatio: 32.4,
        paybackPeriod: 0.6,
        grossMargin: 80,
        churnRate: 15,
      },
      breakEven: {
        month: 16,
        customers: 90,
        mrr: 8910,
      },
      monthlyProjections: [
        { month: 1, revenue: 2475, costs: 7000, profit: -4525, customers: 25, mrr: 2475, runway: 14 },
        { month: 2, revenue: 3465, costs: 7000, profit: -3535, customers: 35, mrr: 3465, runway: 15 },
        { month: 3, revenue: 4851, costs: 7000, profit: -2149, customers: 49, mrr: 4851, runway: 16 },
        { month: 4, revenue: 5940, costs: 8000, profit: -2060, customers: 60, mrr: 5940, runway: 17 },
        { month: 5, revenue: 7128, costs: 8000, profit: -872, customers: 72, mrr: 7128, runway: 18 },
        { month: 6, revenue: 8910, costs: 8000, profit: 910, customers: 90, mrr: 8910, runway: 20 },
        { month: 7, revenue: 10692, costs: 9000, profit: 1692, customers: 108, mrr: 10692, runway: 999 },
        { month: 8, revenue: 12870, costs: 9000, profit: 3870, customers: 130, mrr: 12870, runway: 999 },
        { month: 9, revenue: 15444, costs: 9000, profit: 6444, customers: 156, mrr: 15444, runway: 999 },
        { month: 10, revenue: 17820, costs: 10000, profit: 7820, customers: 180, mrr: 17820, runway: 999 },
        { month: 11, revenue: 19800, costs: 10000, profit: 9800, customers: 200, mrr: 19800, runway: 999 },
        { month: 12, revenue: 21780, costs: 10000, profit: 11780, customers: 220, mrr: 21780, runway: 999 },
      ] as MonthlyProjection[],
    },
  },
  versions: {
    list: [
      { id: 1, version: 1, score: 62, name: 'Initial Version', date: '2025-12-01' },
      { id: 2, version: 2, score: 74, name: 'After Customer Validation', date: '2026-01-15' },
      { id: 3, version: 3, score: 82, name: 'Current Version', date: '2026-02-01' },
    ] as ProjectVersionDB[],
  },
};
