import { View, Text } from '@react-pdf/renderer';
import { pdfStyles } from '../styles';
import { PDFData } from '../prepareData';

interface BusinessScoresPageProps {
  data: PDFData;
}

export function BusinessScoresPage({ data }: BusinessScoresPageProps) {
  const getStatusLabel = (score: number) => {
    if (score >= 80) return { label: 'Strong', style: pdfStyles.statusHigh };
    if (score >= 60) return { label: 'Good', style: pdfStyles.statusMedium };
    if (score >= 40) return { label: 'Needs Work', style: pdfStyles.statusMedium };
    return { label: 'Critical', style: pdfStyles.statusLow };
  };
  
  return (
    <View style={pdfStyles.page}>
      {/* Page Title */}
      <Text style={pdfStyles.sectionTitle}>BUSINESS MODEL CANVAS SCORES</Text>
      <Text style={pdfStyles.text}>
        Detailed breakdown of your business model across 9 key dimensions.
      </Text>
      
      {/* Scores Table */}
      <View style={{ ...pdfStyles.table, marginTop: 20 }}>
        {/* Table Header */}
        <View style={pdfStyles.tableHeader}>
          <Text style={{ ...pdfStyles.tableCellBold, flex: 2 }}>Block</Text>
          <Text style={{ ...pdfStyles.tableCellBold, flex: 1, textAlign: 'center' }}>Score</Text>
          <Text style={{ ...pdfStyles.tableCellBold, flex: 1.5 }}>Status</Text>
        </View>
        
        {/* Table Rows */}
        {data.blockScores.map((block, index) => {
          const status = getStatusLabel(block.score);
          return (
            <View key={index} style={pdfStyles.tableRow}>
              <Text style={{ ...pdfStyles.tableCell, flex: 2 }}>{block.name}</Text>
              <Text style={{ 
                ...pdfStyles.tableCellBold, 
                flex: 1,
                textAlign: 'center',
                fontSize: 11,
              }}>
                {block.score}/100
              </Text>
              <Text style={{ ...pdfStyles.tableCell, ...status.style, flex: 1.5 }}>
                {status.label}
              </Text>
            </View>
          );
        })}
      </View>
      
      {/* Average Score */}
      <View style={pdfStyles.row}>
        <Text style={pdfStyles.heading}>Average Block Score:</Text>
        <Text style={pdfStyles.heading}>
          {Math.round(
            data.blockScores.reduce((sum, block) => sum + block.score, 0) / data.blockScores.length
          )}/100
        </Text>
      </View>
      
      {/* Legend */}
      <View style={{ ...pdfStyles.section, marginTop: 16 }}>
        <Text style={pdfStyles.sectionTitle}>LEGEND</Text>
        <View style={pdfStyles.listItem}>
          <Text style={pdfStyles.bullet}>•</Text>
          <Text style={pdfStyles.listContent}>
            <Text style={{ fontWeight: 700 }}>Strong (80-100):</Text> Well-developed and ready for scaling.
          </Text>
        </View>
        <View style={pdfStyles.listItem}>
          <Text style={pdfStyles.bullet}>•</Text>
          <Text style={pdfStyles.listContent}>
            <Text style={{ fontWeight: 700 }}>Good (60-79):</Text> Solid foundation, minor improvements recommended.
          </Text>
        </View>
        <View style={pdfStyles.listItem}>
          <Text style={pdfStyles.bullet}>•</Text>
          <Text style={pdfStyles.listContent}>
            <Text style={{ fontWeight: 700 }}>Needs Work (40-59):</Text> Requires significant attention.
          </Text>
        </View>
        <View style={pdfStyles.listItem}>
          <Text style={pdfStyles.bullet}>•</Text>
          <Text style={pdfStyles.listContent}>
            <Text style={{ fontWeight: 700 }}>Critical (&lt;40):</Text> High-priority area needing immediate action.
          </Text>
        </View>
      </View>
      
      {/* Footer */}
      <View style={pdfStyles.footer}>
        <Text>Generated by Project Guard AI</Text>
        <Text>Page 2</Text>
      </View>
    </View>
  );
}
