import { View, Text } from '@react-pdf/renderer';
import { pdfStyles } from '../styles';
import { PDFData } from '../prepareData';

interface ExpertAnalysisPageProps {
  data: PDFData;
}

export function ExpertAnalysisPage({ data }: ExpertAnalysisPageProps) {
  const { experts } = data;
  
  const hasExperts = experts.length > 0;
  
  if (!hasExperts) {
    return null; // Don't render page if no experts
  }
  
  return (
    <View style={pdfStyles.page}>
      {/* Page Title */}
      <Text style={pdfStyles.sectionTitle}>EXPERT PERSPECTIVES</Text>
      <Text style={{ ...pdfStyles.text, marginBottom: 12 }}>
        Analysis from multiple expert viewpoints to provide comprehensive insights.
      </Text>
      
      {/* Expert Cards */}
      {experts.map((expert, index) => (
        <View key={index} style={{ ...pdfStyles.card, marginBottom: 10 }} wrap={false}>
          {/* Expert Header */}
          <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
            <Text style={pdfStyles.heading}>{expert.role.toUpperCase()}</Text>
            <Text style={{ ...pdfStyles.heading, fontSize: 11 }}>
              Confidence: {expert.score}%
            </Text>
          </View>
          
          {/* Summary */}
          {expert.perspective && (
            <View style={{ marginBottom: 6 }}>
              <Text style={pdfStyles.text}>{expert.perspective}</Text>
            </View>
          )}
          
          {/* Key Findings */}
          {expert.keyFindings && expert.keyFindings.length > 0 && (
            <View style={{ marginBottom: 6 }}>
              <Text style={{ ...pdfStyles.text, fontWeight: 700, marginBottom: 2 }}>
                Key Findings:
              </Text>
              {expert.keyFindings.map((finding, i) => (
                <View key={i} style={pdfStyles.listItem}>
                  <Text style={pdfStyles.bullet}>•</Text>
                  <Text style={pdfStyles.listContent}>{finding}</Text>
                </View>
              ))}
            </View>
          )}
          
          {/* Concerns */}
          {expert.concerns && expert.concerns.length > 0 && (
            <View style={{ marginBottom: 6 }}>
              <Text style={{ ...pdfStyles.text, fontWeight: 700, marginBottom: 2 }}>
                Concerns:
              </Text>
              {expert.concerns.map((concern, i) => (
                <View key={i} style={pdfStyles.listItem}>
                  <Text style={pdfStyles.bullet}>•</Text>
                  <Text style={pdfStyles.listContent}>{concern}</Text>
                </View>
              ))}
            </View>
          )}
          
          {/* Recommendations */}
          {expert.recommendations && expert.recommendations.length > 0 && (
            <View style={{ marginBottom: 4 }}>
              <Text style={{ ...pdfStyles.text, fontWeight: 700, marginBottom: 2 }}>
                Recommendations:
              </Text>
              {expert.recommendations.map((rec, i) => (
                <View key={i} style={pdfStyles.listItem}>
                  <Text style={pdfStyles.bullet}>•</Text>
                  <Text style={pdfStyles.listContent}>{rec}</Text>
                </View>
              ))}
            </View>
          )}
        </View>
      ))}
      
      {/* Consensus Note */}
      <View style={{ ...pdfStyles.card, marginTop: 10 }}>
        <Text style={pdfStyles.textSmall}>
          Note: These perspectives are generated by AI based on industry best practices and 
          should be validated with real-world domain experts.
        </Text>
      </View>
      
      {/* Footer */}
      <View style={pdfStyles.footer}>
        <Text>AI Guard</Text>
        <Text>Page 6</Text>
      </View>
    </View>
  );
}
